[Build] Generate shaders on build instead of having them checked in

diff --git a/.github/workflows/Linux_build.yml b/.github/workflows/Linux_build.yml
--- a/.github/workflows/Linux_build.yml
+++ b/.github/workflows/Linux_build.yml
@@ -82,6 +82,12 @@ jobs:
         with:
           key: ${{ hashFiles('tools/build/bin/premake5.exe') }}
           path: tools/build/bin/premake5
+      - name: Cache Vulkan SDK
+        id: cache-vulkan-sdk-linux
+        uses: actions/cache@v4
+        with:
+          path: ~/vulkan-sdk
+          key: ${{ runner.os }}-vulkan-sdk-latest
       - name: Setup
         env:
           UBUNTU_BASE: ${{ needs.lint.outputs.UBUNTU_BASE }}
@@ -89,8 +95,24 @@ jobs:
           wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | sudo tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc
           sudo apt-add-repository "deb http://apt.llvm.org/${UBUNTU_BASE}/ llvm-toolchain-${UBUNTU_BASE}-${{ matrix.LLVM_VERSION }} main"
           sudo apt-get -y update
-          sudo apt-get -y install mesa-vulkan-drivers valgrind libc++-dev libc++abi-dev libgtk-3-dev libsdl2-dev libvulkan-dev libx11-xcb-dev clang-${{ matrix.LLVM_VERSION }} ninja-build
-          git submodule update --init --depth=1 -j$(getconf _NPROCESSORS_ONLN) $(grep -oP '(?<=path = )(?!third_party\/(DirectXShaderCompiler|FidelityFX-(CAS|FSR)|premake-(androidndk|export-compile-commands))).+' .gitmodules)
+          sudo apt-get -y install mesa-vulkan-drivers valgrind libc++-dev libc++abi-dev libgtk-3-dev libsdl2-dev libvulkan-dev libx11-xcb-dev clang-${{ matrix.LLVM_VERSION }} ninja-build spirv-tools
+
+          # Install Vulkan SDK
+          if [ '${{ steps.cache-vulkan-sdk-linux.outputs.cache-hit }}' != 'true' ]; then
+            wget -qO vulkan-sdk.tar.xz https://sdk.lunarg.com/sdk/download/latest/linux/vulkan-sdk.tar.xz
+            mkdir -p ~/vulkan-sdk
+            tar -xf vulkan-sdk.tar.xz -C ~/vulkan-sdk
+          fi
+          VULKAN_SDK_VERSION=$(ls ~/vulkan-sdk)
+          echo "VULKAN_SDK=$HOME/vulkan-sdk/$VULKAN_SDK_VERSION/x86_64" >> $GITHUB_ENV
+          echo "$HOME/vulkan-sdk/$VULKAN_SDK_VERSION/x86_64/bin" >> $GITHUB_PATH
+
+          # Verify shader tools are available
+          which glslangValidator && glslangValidator --version || echo "Warning: glslangValidator not found"
+          which spirv-opt && spirv-opt --version || echo "Warning: spirv-opt not found"
+          which spirv-dis || echo "Warning: spirv-dis not found"
+
+          git submodule update --init --depth=1 -j$(getconf _NPROCESSORS_ONLN) $(grep -oP '(?<=path = )(?!third_party\/(DirectXShaderCompiler|premake-(androidndk|export-compile-commands))).+' .gitmodules)
           if [ '${{ steps.cache.outputs.cache-hit }}' != 'true' ]; then
             ./xenia-build.py premake
             cp third_party/premake-core/bin/release/premake5 tools/build/bin
